### ISSUE TITLE
DGFIP documentation page redirects to the CAF schema

### ISSUE THREAD

**Issue by adelcasse** [fabmob/CMS#4]
In this page : https://github.com/fabmob/CMS/blob/additional_models_and_fixes/conceptual_model/fr-dgfip-information.md

The title mentions "CAF" instead of DGFIP and the link to the schema sends to the CAF schema.

I didn't look further at the content so I didn't check the other informations in the page.

**Comment by jthiard** [comment]
Thanks for the report I'll fix the link and title and check the whole page.

**Comment by jthiard** [comment]
Fixed in 500217b82a2c9c28a831dbaf7290c356ae399454
